### ISSUE TITLE
Markdown Docs?

### ISSUE THREAD

**Issue by MynockSpit** [RecursiveThinking/recursive_thinking_website_tech_docs#6]
Markdown is way easier to write than HTML. Is it worth it to look into rendering markdown instead of or alongside HTML?

**Comment by sethborne** [comment]
sorry - maybe I'm not quite getting the question, but could I (making a big assumption) put this to the question of - "why are we doing a tech doc website vs just outlining tech docs in .md?"

**Comment by MynockSpit** [comment]
No, actually. I was merely thinking that if we had a markdown parser built into the website, writing docs would be easier. It has the added benefit of rendering on GitHub, so you wouldn’t need to pull down the site if you didn’t want to, but mostly I just love markdown.

**Comment by sethborne** [comment]
Could you give an example/tutorial...I'll admit - I'm not quite following what your getting at, but I think if I see an example, I'll understand?

**Comment by MynockSpit** [comment]
Instead of writing pure HTML, we'd write the docs in markdown. Then, when the server renders the page it does magic and converts that markdown to html. (Think what github does with .md files.)

Here's an example from a markdown parser library: https://marked.js.org/demo

Definitely not necessary, but it's mainly for those of us who would much rather write this:

```
- list **item** 1
- list item 2
```

than this:

```html
<ul>
  <li> list <span style="font-weight: bold">item</span> 1 </li>
  <li> list item 2 </li>
</ul>
```

**Comment by sethborne** [comment]
OMG...approaching the HTML/MD event horizon

**Comment by sethborne** [comment]
and...don't think we'll be doing this...sorry...

**Comment by MynockSpit** [comment]
No worries. :)
